// 大陆主要城市经度(东经,度),用于真太阳时校正。
// 只收录使用北京时间、且适用大陆夏令时历史的城市。
export const CITIES: ReadonlyArray<{ name: string; longitude: number }> = [
  { name: '北京', longitude: 116.4 },
  { name: '天津', longitude: 117.2 },
  { name: '上海', longitude: 121.5 },
  { name: '重庆', longitude: 106.5 },
  { name: '哈尔滨', longitude: 126.6 },
  { name: '长春', longitude: 125.3 },
  { name: '沈阳', longitude: 123.4 },
  { name: '大连', longitude: 121.6 },
  { name: '呼和浩特', longitude: 111.7 },
  { name: '石家庄', longitude: 114.5 },
  { name: '太原', longitude: 112.5 },
  { name: '济南', longitude: 117.0 },
  { name: '青岛', longitude: 120.4 },
  { name: '郑州', longitude: 113.6 },
  { name: '西安', longitude: 108.9 },
  { name: '兰州', longitude: 103.8 },
  { name: '西宁', longitude: 101.8 },
  { name: '银川', longitude: 106.2 },
  { name: '乌鲁木齐', longitude: 87.6 },
  { name: '拉萨', longitude: 91.1 },
  { name: '成都', longitude: 104.1 },
  { name: '贵阳', longitude: 106.6 },
  { name: '昆明', longitude: 102.7 },
  { name: '南宁', longitude: 108.3 },
  { name: '广州', longitude: 113.3 },
  { name: '深圳', longitude: 114.1 },
  { name: '海口', longitude: 110.3 },
  { name: '福州', longitude: 119.3 },
  { name: '厦门', longitude: 118.1 },
  { name: '南昌', longitude: 115.9 },
  { name: '长沙', longitude: 112.9 },
  { name: '武汉', longitude: 114.3 },
  { name: '合肥', longitude: 117.3 },
  { name: '南京', longitude: 118.8 },
  { name: '杭州', longitude: 120.2 },
  { name: '苏州', longitude: 120.6 },
  { name: '宁波', longitude: 121.6 },
  { name: '温州', longitude: 120.7 },
];
